GET {{host}}/dinners
Authorization: Bearer e yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMTkwZTYyZS05MzEwLTQ3ZTUtOGM5ZC00YzA0ZDk2YjU5NjgiLCJqdGkiOiJlMjgyNDlhMS1iNjliLTRiNDctODhmYi0wN2NkY2E2MTUzZDMiLCJnaXZlbl9uYW1lIjoiQm9nZGFuIiwiZmFtaWx5X25hbWUiOiJLYWxpbm92c2tpIiwiZXhwIjoxNzA0MjA5NjM4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.q7jcsHmXsNuRI1hBVqZV-O1JkHWsOEmX2nUmwOsZlGE
Content-Type: application/json
